version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.08
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Give permission to gradlew
          command: chmod +x ./gradlew

      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "build.gradle" }}
            - gradle-cache-v1-

      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apks

workflows:
  version: 2
  build_and_test:
    jobs:
      - run:
            name: Run Unit Tests
            command: ./gradlew test

